### ISSUE TITLE
distutils reports invalid version (-0.5.x instead of 0.5.x)

### ISSUE THREAD

**Issue by badshah400** [gwpy/gwosc#55] opened 2020-08-03 21:00 UTC
When building `gwosc` with python 3.8, `distutils` reports an invalid version (-0.5.5 instead of 0.5.5). Among other things, this causes problems with version checks when running tests for `gwpy` involving `gwosc`.

```
[    9s] /usr/lib/python3.8/site-packages/setuptools/dist.py:481: UserWarning: The version specified ('-0.5.5') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```

**Comment by duncanmmacleod** [comment] 2020-08-04 08:51
Hi @badshah400, I cannot reproduce that, can you please post what command you are running, what operating system you are on, and what python distribution you are using?

**Comment by badshah400** [comment] 2020-08-04 11:25
I am building packages for openSUSE.
Specifically, openSUSE Tumbleweed x86_64, python 3.8.4. Full package is here: <https://build.opensuse.org/package/show/science/python-gwosc>, but I attach the full build log here for your information.
[_log.zip](https://github.com/gwpy/gwosc/files/5021788/_log.zip)

**Comment by duncanmmacleod** [comment] 2020-08-04 12:33
Ok, so the issue here is resolving the version from `versioneer.py` when you aren't using the git repo. The solution is to use the tarball from pypi.org, and not the auto-build one from github.com. Can you use the `%pypi_source` macro in your spec file? If not, the correct `Source` URL is:

https://pypi.io/packages/source/g/%{modname}/%{modname}-%{version}.tar.gz

**Comment by badshah400** [comment] 2020-08-04 13:16
Yes that did the trick. Thanks!

**Closed** 2020-08-28 15:18 UTC
